name: Node.js CI

on: [push]

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2

        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build API
        run: yarn build

      - name: Run API
        run: yarn dev
