name: Node.js CI

on: [push]

jobs:
  build-dev-api:
    name: Test API Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build API
        run: yarn build
  deploy-dev-api:
    needs: build-dev-api
    name: Deploy dev API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Docker Hub Authentication
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: mgraman/sd-dev

      - name: Create env vars
        run: touch ./server/.env.production

      - name: list dir
        run: ls

      - name: Set .env.production
        run: |
          cat >> ./server/.env.production <<EOL 
          SESSION_SECRET=${{secrets.DEV_SESSION_SECRET}}
          CORS_DOMAIN=${{secrets.DEV_CORS_DOMAIN}} 
          CORS_ORIGIN=${{secrets.DEV_CORS_ORIGIN}} 
          REDIS_URL=${{secrets.DEV_REDIS_URL}}
          EOL

      - name: View
        run: cat ./server/.env.production

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./server/Dockerfile
