name: Production CI

on:
  release:
    branches: [prod]

jobs:
  build-prod-api:
    name: Test API Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build API
        run: yarn build
  deploy-prod-api:
    needs: build-prod-api
    name: Deploy Production API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Docker Hub Authentication
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: mgraman/sd-prod

      - name: Create env vars
        run: touch ./server/.env

      - name: Set .env
        run: |
          cat >> ./server/.env.production <<EOL
          DATABASE_URL=${{secrets.PROD_DATABASE_URL}}
          SESSION_SECRET=${{secrets.PROD_SESSION_SECRET}}
          CORS_DOMAIN=${{secrets.PROD_CORS_DOMAIN}} 
          CORS_ORIGIN=${{secrets.PROD_CORS_ORIGIN}} 
          REDIS_URL=${{secrets.PROD_REDIS_URL}}
          PORT=4000
          EOL

      - name: Get NPM Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./server

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-api-${{ steps.package-version.outputs.current-version}}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./server/dockerfiles/prod-ci.Dockerfile
