name: Production CI

on:
  release:
    branches: [prod]

jobs:
  test-prod-api:
    name: Test API Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build API
        run: yarn build
  build-docker-prod-api:
    needs: test-prod-api
    name: Build & Push Docker Container for Production API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Docker Hub Authentication
        uses: docker/login-action@3f83d7b89cb3b72c3cb1c57dd6faaa722bb5895c
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@3a3bb3a81753dc99f090d24ee7e5343838b73a96
        with:
          images: mgraman/sd-prod

      - name: Create env vars
        run: touch ./server/.env

      - name: Set .env
        run: |
          cat >> ./server/.env <<EOL
          DATABASE_URL=${{secrets.PROD_DATABASE_URL}}
          SESSION_SECRET=${{secrets.PROD_SESSION_SECRET}}
          CORS_DOMAIN=${{secrets.PROD_CORS_DOMAIN}} 
          CORS_ORIGIN=${{secrets.PROD_CORS_ORIGIN}} 
          REDIS_URL=${{secrets.PROD_REDIS_URL}}
          PORT=4000
          EOL

      - name: Get NPM Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ./server

      - name: Build and push Docker image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-api-${{ steps.package-version.outputs.current-version}}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./dockerfiles/prod-ci.Dockerfile
